include: "/views/autogenerated_views/view_1.view.lkml"
include: "/views/autogenerated_views/view_2.view.lkml"
include: "/views/refined_views/r_view_1.view.lkml"
include: "/views/refined_views/r_view_2.view.lkml"

explore: bugged {
  label: "Explore that fails linting (E2) (foreign_key)"
  from:  view_2
  join: view_1 {
    foreign_key: pk2_item_id
    type: left_outer
    relationship: many_to_one
  }
}