include: "/views/autogenerated_views/view_2.view.lkml"

view: +view_2 {
  dimension: pk_composite {
    primary_key: yes
    hidden: yes
    sql: CONCAT(${pk2_date}, ${pk2_item_id}) ;;
  }
  dimension: pk2_date {
    hidden: yes
    sql: ${date} ;;
  }
  dimension: pk2_item_id {
    hidden: yes
    sql: ${item_id} ;;
  }

  measure: count {
    hidden: yes
  }

  measure: m_visits {
    group_label: "Unique item-visits"
    type: count_distinct
    sql: ${item_id} ;;
  }

}
