include: "/views/autogenerated_views/view_1.view.lkml"

view: +view_1 {
  
  dimension: pk1_item_id {
    primary_key: yes
    hidden: yes
    sql: ${item_id} ;;
  }
  
  measure: count {
    hidden: yes
  }
  
}
